### ISSUE TITLE
GPRealEstate Extended Features

### ISSUE THREAD

**Issue by NullCase** [NullCase/GPRealEstate#3]
A list of simple features to improve GPRealEstate.
1. Mail a land claim seller to inform them that "[Player] has bought your land claim (coords) for $$
2. Offer to buy command: Type "/gpre offer [price in $]" while standing in a land claim. Mail the claim owner with the player's name, the offer price, and the claim.
3. When a player creates a sign to sell/auction/rent a claim, broadcast it to the server. (optional in config)
4. A command like "/gpre list sale" which lists top level claims that are for sale. /gpre list auction (for auctions). /gpre list manage (for subclaims on sale).
5. Ability to sell pets/horses like real estate? How would it work?

**Comment by EtienneDx** [comment]
Hey NullCase, I've been searching for some mc stuff to do since I have a little free time, and did both 1 and 3 with normal messages tonight (checkout [my fork](https://github.com/EtienneDx/GPRealEstate) if you want to see the code). 

For the number 2, it depends on the mail plugin used (could make it for multiple plugins, to see ^^). 

For number 4, the current system isn't able to manage this perfectly, since all sales are entirely relying on signs, and number 5 would be another plugin alltogether as well.

Btw, if this isn't of actuality anymore (which I could understand), pls tell me, I prefer to work on usefull stuff haha

**Comment by NullCase** [comment]
sent you mail. :)

**Comment by NullCase** [comment]
the auction related features are present in GPAuctions now. will update this on next pass.

**Comment by NullCase** [comment]
we use EssentialsX for mail.

**Comment by NullCase** [comment]
https://github.com/EssentialsX/Essentials

**Comment by EtienneDx** [comment]
Perfect, will use 😊

**Comment by EtienneDx** [comment]
Alright, here’s the repo and the wiki page I started quickly, with the link to the beta release : 
https://github.com/EtienneDx/RealEstate/wiki
