### ISSUE TITLE
Initial testing/audit

### ISSUE THREAD

**Issue by NullCase** [NullCase/GPRealEstate#6]
@EtienneDx i don't know how to code, so maybe this is a dumb question :)

Do you have a link to the .jar file? because then I can start testing.

**Comment by EtienneDx** [comment]
Its in the release section, under the asset subsection

**Comment by EtienneDx** [comment]
I’ve just seen that’s not the new repo, so here it is again : 
GitHub.com/EtienneDx/RealEstate/releases

**Comment by NullCase** [comment]
ah yep, i was looking at the fork.

**Comment by NullCase** [comment]
@robomwm Want to make some $ auditing code?

Maybe just an hour worth checking the code here:
 https://github.com/EtienneDx/RealEstate/commits/master

Background: @EtienneDx has recoded GPRealEstate to include rentals, leases, extended features (from [issues](https://github.com/NullCase/GPRealEstate/issues))

**Comment by RoboMWM** [comment]
Is there a reason why he didn't fork any repo? Makes it hard to create a diff :c

**Comment by EtienneDx** [comment]
@RoboMWM I did but then I decided to recode it all, just keeping the basic ideas, because leasing and renting would require to persist data, so I figured I might as well persist the sales too

**Comment by EtienneDx** [comment]
So yeah a diff wouldn't bring out much, since it's not the same base at all

**Comment by RoboMWM** [comment]
Still no reason not to fork. At least then I could see the recode. Unless you mean that you literally started from scratch...?

**Comment by EtienneDx** [comment]
I literally did

**Comment by NullCase** [comment]
Late in the day here. Will come back tomorrow. Thanks guys.

**Comment by RoboMWM** [comment]
Not sure what to audit, but some tips:
- Packages, please.
- DataStore seems to be quite similar for a "start from scratch." Not a big deal but having the singular `DataStore` pattern can be improved upon IMO (see v20 rewrite of GP for my rendition, pretty sure others also have better design patterns.)
  - Might be okay since it just seems to be just config tho. Should be then named as such IMO.
- Unsure why you're key-ing on String when you could key on Integer for claimSell/Rent/Lease map (in TransactionsStore).
- Though it could be github rendering screwing things up lately, `REListener` seems to have a mix of tabs and spaces/mismatched indents.
  - Also, I didn't think it was also the command handler, maybe it could be broken up a bit.
  - You may want to consider using ACF or separate CommandExecutors to handle the commands instead of bundling them up into a long if-else-if sequence

**Comment by EtienneDx** [comment]
Alright, thanks for the tips, as you may have seen above, I never programmed for bullit/spigot before, and very little in Java, so I'm freestyling a little. You're right, I did keep the syntax of the DataStore variables, but recoded how they are saved (and yes, it's only config).

Indeed, I should breakup things into packages, your totally right there. 

Why do I key on string, that's a very good question x)

for the tabs and spaces, that could be a thing, I'll check it.

Never heard of ACF, I will look into it, and probably put the commands elsewhere as well.

Thanks for the tips again :)

**Comment by RoboMWM** [comment]
https://aikar.github.io/commands/

Haven't used it myself (yet) but it's very much annotation-based, eliminating a lot of boilerplate code.

**Comment by RoboMWM** [comment]
Also, please look into using maven (or gradle) to build your project and automatically manage dependencies.

**Comment by EtienneDx** [comment]
Ok, will do

**Comment by EtienneDx** [comment]
Thanks a lot for the tips above @RoboMWM,
I switched to maven and was just wondering if you could help me out a little more, is it possible to run the maven build to create the jar directly inside a test server plugins folder?

**Comment by RoboMWM** [comment]
Yes, but that's not recommended, especially if others want to build and test (since you'll probably have a hardcoded path that won't work when run on other machines/by other people). Instead just have a bash script copy the target or append it to your command, e.g. `... && cp the.jar wherever/you/want/`

**Comment by NullCase** [comment]
The hardcoded path issue has surfaced before in exactly the way you describe @RoboMWM Now I have an explanation for what happened. Also, payment sent.

**Comment by NullCase** [comment]
@EtienneDx it sounds like some optimizations were suggested.

Do you think I should test this release or wait to provide testing feedback in the next one?

**Comment by EtienneDx** [comment]
You can already test this one, but indeed there will be quite some
optimizations in the next one

**Comment by NullCase** [comment]
OK, just to be prudent with time I will wait for the next one.

**Comment by EtienneDx** [comment]
Alright, I''ve finished for this release : https://github.com/EtienneDx/RealEstate/releases
Everything is now in place, except for the mails, which will normally come soon

**Comment by EtienneDx** [comment]
@RoboMWM hey, I've installed ACF, but it makes me a very large jar file (5 Mo), for a not so large plugin (compared to vault which is 0.2 Mo and GP which is 0.3 Mo). Do you know if this is normal or if I missed something in the pom.xml file?
**EDIT:** Just forgot the <scope>provided</scope> :/

**Comment by RoboMWM** [comment]
You're using maven to shade, right?

**Comment by EtienneDx** [comment]
Yes, but the problem was in the dependencies, I didn't specify the scope so they were all copied inside the jar

**Comment by RoboMWM** [comment]
Yea, unless you set the shade plugin to only include certain dependencies it will include everything that doesn't have provided scope.

**Comment by EtienneDx** [comment]
Ok, so that explains it :)
